routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\HomeController::class, 'home'])->name('home');

Route::get('/users/register', [\App\Http\Controllers\UsersController::class, 'register'])->name('users.register');

Route::post('users', [\App\Http\Controllers\UsersController::class, 'store'])->name('users.store');

Route::get('/login', [\App\Http\Controllers\SessionsController::class, 'create'])->name('sessions.login');
Route::post('login', [\App\Http\Controllers\SessionsController::class, 'store'])->name('sessions.store');
Route::delete('/logout', [\App\Http\Controllers\SessionsController::class, 'destroy'])->name('sessions.delete');

Route::resource('genres', \App\Http\Controllers\GenresController::class)->only(['index', 'show']);

Route::resource('libCards', \App\Http\Controllers\LibCardsCotroller::class)->only(['show']);

Route::resource('items', \App\Http\Controllers\ItemsController::class)->only(['create', 'store']);

Route::put('items/{item}', [\App\Http\Controllers\ItemsController::class, 'returnBook'])->name('items.return');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Item extends Model
{
    use HasFactory;

    protected $fillable = ['lib_card_id', 'book_id', 'return_date', 'return_book'];

    /**
     * @return BelongsTo
     */
    public function libCard()
    {
        return $this->belongsTo(Lib_card::class);
    }

    /**
     * @return BelongsTo
     */
    public function book()
    {
        return $this->belongsTo(Book::class);
    }
}

app/Http/Controllers/ItemsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Item;
use App\Models\Lib_card;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ItemsController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return Factory|View|\Illuminate\Http\RedirectResponse|Response
     */
    public function create(Request $request)
    {
        if (!session()->exists('lib_card_name')) {
            return redirect()->route('home');
        }
        $book = Book::find($request->input('book_id'));
        return view('items.create', compact('book'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|Response
     */
    public function store(Request $request)
    {
        $item = new Item($request->all());
        $item->save();
        return redirect()->route('home')->with('success', 'Book added!');
    }

    /**
     * @param Request $request
     * @param Item $item
     * @return \Illuminate\Http\RedirectResponse
     */
    public function returnBook(Request $request, Item $item)
    {
        $item->update($request->all());
        $item->return_book = true;
        $item->save();
        return redirect()->back();
    }
}

resources/views/items/create.blade.php
@extends('layouts.base')

@section('content')

    @include('notifications.alerts')


    <form action="{{route('items.store')}}" method="post">
        @csrf

        <input type="hidden" name="lib_card_id" value="{{\App\Models\Lib_card::where('name', session()->get('lib_card_name'))->first()->id}}">

        <div class="form-group">
            <label for="book_id">Book:</label>
        <select class="form-control" name="book_id" id="book_id">
            <option class="form-control" selected value="{{$book->id}}">{{$book->author}} {{$book->title}}</option>
        </select>
        </div>

        <div class="form-group">
        <label for="return_date">Return date</label>
        <input class="form-control" type="date" name="return_date" id="return_date">
        </div>

        <button type="submit" class="btn btn-primary">Take book</button>

    </form>

@endsection