routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\HomeController::class, 'home'])->name('home');

Route::get('/users/register', [\App\Http\Controllers\UsersController::class, 'register'])->name('users.register');

Route::post('users', [\App\Http\Controllers\UsersController::class, 'store'])->name('users.store');

Route::get('/login', [\App\Http\Controllers\SessionsController::class, 'create'])->name('sessions.login');
Route::post('login', [\App\Http\Controllers\SessionsController::class, 'store'])->name('sessions.store');
Route::delete('/logout', [\App\Http\Controllers\SessionsController::class, 'destroy'])->name('sessions.delete');

Route::resource('genres', \App\Http\Controllers\GenresController::class)->only(['index', 'show']);

Route::resource('libCards', \App\Http\Controllers\LibCardsCotroller::class)->only(['show']);

Route::resource('items', \App\Http\Controllers\ItemsController::class)->only(['create', 'store']);

Route::put('items/{item}', [\App\Http\Controllers\ItemsController::class, 'returnBook'])->name('items.return');

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Genre extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'desc'];

    /**
     * @return HasMany
     */
    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

app/Http/Controllers/GenresController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genre;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class GenresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|Response
     */
    public function index()
    {
        $genres = Genre::paginate(1);
        return view('genres.index', compact('genres'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Genre  $genre
     * @return Factory|View|Response
     */
    public function show(Genre $genre)
    {
        return view('genres.show', compact('genre'));
    }
}

resources/views/genres/index.blade.php
@extends('layouts.base')

@section('content')

    <h1>Books of all genres: </h1>

    @if($genres->count()>0)

        @foreach($genres as $genre)

            <h4>{{$genre->name}}</h4>

            <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach($genre->books as $book)

                    <div class="col mb-1">
                        <div class="card" style="max-width: 200px">
                            <img src="{{asset('/storage/' . $book->picture)}}" class="card-img-top" alt="{{asset('/storage/' . $book->picture)}}">
                            <div class="card-body">
                                <h5 class="card-title">{{$book->author}}</h5>
                                <p class="card-text">{{$book->title}}</p>
                                @if(session()->exists('lib_card_name'))
                                    @if(is_null(\App\Models\Lib_card::where('name', session()->get('lib_card_name'))->first()->items->where('book_id', $book->id)->first()) or
                                        \App\Models\Lib_card::where('name', session()->get('lib_card_name'))->first()->items->where('book_id', $book->id)->first()->return_book == true)

                                    <form action="{{route('items.create')}}" method="post">
                                        @csrf
                                        @method('get')
                                        <input type="hidden" name="book_id" value="{{$book->id}}">
                                        <button class="btn btn-outline-primary">Order</button>
                                    </form>
                                    @endif
                                @endif
                            </div>
                        </div>

                    </div>

            @endforeach
            </div>

        @endforeach

    @else

        <p>no genres</p>

    @endif

    <div class="row justify-content-md-center p-5">

        <div class="col-md-auto">

            {{ $genres->links('pagination::bootstrap-4') }}

        </div>

    </div>

@endsection

resources/views/genres/show.blade.php
@extends('layouts.base')

@section('content')

    <h1>Books of genre "{{$genre->name}}": </h1>

    @if($genre->books->count()>0)

            <div class="row row-cols-1 row-cols-md-3 g-4">
                @foreach($genre->books as $book)

                    <div class="col mb-1">
                        <div class="card" style="max-width: 200px">
                            <img src="{{asset('/storage/' . $book->picture)}}" class="card-img-top" alt="{{asset('/storage/' . $book->picture)}}">
                            <div class="card-body">
                                <h5 class="card-title">{{$book->author}}</h5>
                                <p class="card-text">{{$book->title}}</p>
                                @if(session()->exists('lib_card_name'))
                                    <form action="{{route('items.create')}}" method="post">
                                        @csrf
                                        @method('get')
                                        <input type="hidden" name="book_id" value="{{$book->id}}">
                                        <button class="btn btn-outline-primary">Order</button>
                                    </form>
                                @endif
                            </div>
                        </div>

                    </div>

                @endforeach
            </div>

    @else

        <p>no genres</p>

    @endif

@endsection